Lesson 7
OnlyReFLeX/qna pull request #5
Opened 2018-04-22 22:24 UTC by OnlyReFLeX

2018-04-23 10:40 UTC, vkurennov requested changes

2018-04-23 10:40 UTC, vkurennov commented on app/assets/javascripts/answers.js
> +ready = function() {
можно сразу писать `var ready = ...`, без отдельного объявления переменной

2018-04-23 10:40 UTC, vkurennov commented on app/assets/javascripts/answers.js
> +$(document).on('turbolinks:load',ready);
Пробел после запятой

2018-04-23 10:40 UTC, vkurennov commented on app/assets/javascripts/questions.js
> +$(document).on('turbolinks:load',ready);
И тут пробела не хвататет после запятой

2018-04-23 10:40 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  before_action :authenticate_user!, only: [:create, :destroy, :update]
А почему для select_best не нужна аутентификация?

2018-04-23 10:40 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if current_user&.author_of?(@answer.question)
Добавь аутентификацию для этого экшена, тогда не нужно будет здемь применять safe navigation. ну и в любом случае, это действие доступно только залогиненным юзерам

2018-04-23 10:40 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      render :select_best
Это лишнее, т.к. если не указан рендеринг или редирект явно, то рендерится одноименный экшену вид.

2018-04-23 10:40 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to @answer.question, alert: "You can not delete someone else's answer"
Удаление у нас через ajax должно работать. А редирект в ajax запросах не имеет смысла, потому что он происходит в фоне, пользователь ничего не видит, т.к. браузер не отображает html-код, полученный в фоне. Тут надо ошибку на уровне js-показывать: ставим флеш-сообщение и в js показыаем его, если оно есть

2018-04-23 10:40 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to @answer.question, alert: 'You do not have enough rights'
Редирект при ajax-запросах не имеет смысла

2018-04-23 10:40 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      @answer.select_best_answer
Не нужно название класса включать в название метода, получается слишком громоздко. Гораздо лучше смотрится вызов `@answer.select_best`

2018-04-23 10:40 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to @answer.question, alert: 'You are not the author of this question'
Редирект при ajax-запросах не имеет смысла

2018-04-23 10:40 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +      redirect_to question_params, alert: "You can not delete someone else's question"
Редирект при ajax-запросах не имеет смысла

2018-04-23 10:40 UTC, vkurennov commented on app/models/answer.rb
> +  def select_best_answer
В методе несколько апдейтов, в этом случае нужно применять [транзакцию](http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html), чтобы изменения были атомарынми, т.е. либо все апдейты прошли, либо ни одного

2018-04-23 10:40 UTC, vkurennov commented on app/models/answer.rb
> +      old_best_answer = question.answers.find_by(best: true)
Лишний запрос получается. Сначала в if ты делаешь запрос, но без выборки записи, а тут тот же запрос, но уже с выборкой. Гораздо лучше сделать один раз find_by и проверить вернул он объект или nil

2018-04-23 10:40 UTC, vkurennov commented on app/views/questions/show.html.slim
>      = render @answers
Если уже есть лучший ответ, то при загрузке страницы он должен отображаться первым, у тебя же он будет на том месте, где был в общем списке

2018-04-23 10:40 UTC, vkurennov commented on app/views/questions/show.html.slim
> += render 'question_show', question: @question
Зачем какой-то question_show, когда можно назвать паршл _question и рендерить его так: `render @question`

2018-04-23 10:40 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      expect(assigns(:answer)).to eq answer
В юнит-тестах дейтсвует правило "один тест - один expect"

2018-04-23 10:40 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      expect(answer.best) == true
Так это не работает, для теста обязательно должен быть вызов `to`, ну и есть другой синтаксис,более краисвый: `expect(answer).to be_best`

2018-04-23 10:40 UTC, vkurennov commented on spec/models/answer_spec.rb
> +      expect(best_answer.best) == false
1. Опять же один тест - один expect
2. Такие проверки не работают, ты можешь убрать часть с == true или изменить код самого метода на противоположный и увидеть, что тесты проходят. Потому что на самом деле никакого сравнения тут нет, нужна часть с `to`
3. Используй синтаксис вида `expect(answer).to be_best`

2018-04-23 13:28 UTC, OnlyReFLeX commented on app/views/questions/show.html.slim
>      = render @answers
В questions_controller определяется сортировка

```@answers = @question.answers.order(best: :desc, created_at: :desc)```

2018-04-23 16:31 UTC, vkurennov requested changes

2018-04-23 16:31 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if current_user.author_of?(@answer)
А если нет, стоит показать сообщение

2018-04-23 16:31 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +      redirect_to question_params, alert: "You can not delete someone else's question"
Так а чего редирект остался? И что за странный аргумент -  question_params? Там же тело и заголовок, куда редиректо-то?

2018-04-23 16:31 UTC, vkurennov commented on app/models/answer.rb
> +      self.update!(best: true)
self тут не нужен

2018-04-23 16:31 UTC, vkurennov commented on app/models/answer.rb
> +      old_best.update!(best: false) unless old_best.nil?
Лучше переписать с if: `if old_best`

2018-04-23 16:31 UTC, vkurennov commented on spec/features/answers/select_best_answer_spec.rb
> +      expect(page).to_not have_link "Choose best"
Этого как-то маловато. Что с того, что исчезла ссылка? Как нам проверить, что выбранный ответ действительно стал лучшим? Надо как минимум проверить, что она стал первым (значит, ответов должно быть несколько), еще можно проверить внутри какого селектора он оказался, если лучший ответ как-то выделяется через классы или id  элементов

2018-04-23 16:31 UTC, vkurennov commented on spec/features/answers/select_best_answer_spec.rb
> +feature 'Create answers', %q{
Нужен сценарий, когда один лучший ответ уже есть и автор выбирает другой

2018-04-24 08:43 UTC, vkurennov approved these changes

2018-04-24 20:59 UTC, merged